### ISSUE TITLE
Little endianess incorrect

### ISSUE THREAD

**Issue by encojosh** [Ericbla/binary-parser#19]
`let parser = new Parser()
    .endianess("little")
    .bit4("a")
    .bit1("b")
    .bit1("c")
    .bit1("d")
    .bit1("e")
    .uint16("f")
    .array("g", {
        type: "uint8",
        readUntil: "eof"
    });`

Encoding and then parsing an object using this parser in little endian mode does not result in the same object, but it does in big endian mode.

**Comment by Ericbla** [comment]
Hello, you are perfectly right. With 'little' endian mode, the encoding is different than the parsing for bit fields.

For integer based types, the endianess defines the **BYTE** order.
For bits fields, the author of the Parser used a kind of BITs ordering for the aggregated bits fields (up to 32bits). This is a bit confusing, so for the encoding I have prefered to use more simple mechanism where we always consider bit fields definition from left to right (higher to lower bits) and top to down (lower to higher memory address).

So from parsing point of view, when you use a set of bits fields in  little endian mode, you reverse the order of bit fields
`Parser.start().endianess("little").bit4("a").bit3("b").bit3("c").bit6("d");`
is equivalent to have [d c b a] in stream of bits.

And this even more confusing when you use for example:
`Parser.start().endianess("little").bit16("a").bit16("b");`
In this case you will have [b a]  but b and a values will have Big Endian representation !


Nethertheless if you want to have a full symetric  parsing/encoding of bit fields, I have added an option that allow the encoding process to mimic the decoding one.
This is available since release 1.4.5 and you must add to your parser definition:
```
Parser.start()
  .endianess("little")
  .setEncoderOptions({bitEndianess: true})    // Add this
  .bit4("a")
  .bit3("b")
  .bit3("c")
  .bit6("d");
```
See also the test in `test/zz_encoder_bugs.js` to see how it works.

Regards.

--
Eric
