### ISSUE TITLE
[bug] ReferenceError: SmartBuffer is not defined

### ISSUE THREAD

**Issue by jmarceli** [Ericbla/binary-parser#2]
Hi,
Many thanks for this super useful package.

I'm using it in my current project but I have one annoying issue, which is that I can't run my Jest based tests with parser based encoding. Here is the error message:

```
    ReferenceError: SmartBuffer is not defined

      at Parser.compiledEncode (evalmachine.<anonymous>:5:19)
      at Parser.Object.<anonymous>.Parser.encode (node_modules/binary-parser-encoder/lib/binary_parser.js:455:15)
      at input.reduce (src/myfile.js:196:14)
          at Array.reduce (<anonymous>)
      at download (src/myfile.js:193:16)
      at Object.test (src/myfile.test.js:9:12)
``` 
EDIT
I slim down my codebase to only a test file:

```
const { Parser } = require('binary-parser-encoder');

const parser = new Parser()
  .uint32be('data_0');

test('test', () => {
  const a = parser.encode({ data_0: '123' })
    .toString('hex');
  expect(a).toEqual('0000007b');
});
```

I would appreciate any help.

What is even stranger this test works perfectly in codesandbox https://codesandbox.io/s/m3z1wz265x

**Comment by jmarceli** [comment]
It seems to be similar to https://github.com/facebook/jest/issues/3703, so the problem is connected with Jest and globals in vm

**Comment by Ericbla** [comment]
Yes, you've found yourself the problem of Jest.
My initial implementation of the encoder was built with Nodejs Buffer, but the main drawback is that you need to dimension that buffer before you run the encoder. That's why I've replaced it by SmartBuffer that dynamically and automatically grows when you write data int it.
(However, if you are interested in it, here is the commit where I've replaced the Buffer by the SmartBuffer: https://github.com/Ericbla/binary-parser/commit/775553b8df1bbb01a338b470c7cda8907064c38b)

You can also consider to use another test framework. For example **Mocha** works well with this library.

B.R.
--
Eric
