### ISSUE TITLE
String padded with space (0x20) instead of null (0x0) when reencoding

### ISSUE THREAD

**Issue by p0358** [Ericbla/binary-parser#20]
Suppose I have this code
```js
parser.string(name, {
    length: string_size,
    zeroTerminated: false,
    stripNull: true
});
```
where string_size is some fixed length.
The thing appears to be parsed nicely, but when I try to re-encode, the missing fields are filled with spaces. A temporary workaround I found is 
```js
encoder: item => (item+'') + Array(1024).fill("\0").join("") // 1024 being some arbitrary number that's bigger than string_size
```
since then the string is just capped at its maximum length, and only then my output file is equal to input.

**Comment by p0358** [comment]
Just found #17, and adding `padd: "\0"` option did work; I think this should be the default (to match the decoder)

**Comment by Ericbla** [comment]
Thanks for reporting this drawback, but it was already mentioned in the Readme (when using `stripNull`and `length` together in string).

However, I have done a small change to have the default `padd` character to be set to *null* when `stripNull`and `length`are used together.
(But you can still change the behavior on encoding by using `padd` and `padding` options.

Adding some tests allowed me to discover other bugs with the `zeroTerminated` option.
- There was a bug in the decoding part of the parser when a *null* character sit exactly at the end of the sting (determined by the `length` option).  This *null* character was kept in the string.
- I have also changed the encoding behavior to respect the `length` option, so that decoding and encoding are also symetric in this case.
